sudo: false
language: node_js
node_js:
  - 0.12.2

notifications:
  email: false

addons:
  code_climate:
    repo_token: CODECLIMATE_REPO_TOKEN=477c6e6416b854edcd23bbd313b0ab81dd004774ed35aa6dc8be0b0f29739876

after_script:
  - cat lcov.info | codeclimate
